// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Supermarket.Infrastructure.Migrations
{
    [DbContext(typeof(SuperMarketDbContext))]
    partial class SuperMarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("ProductBatch", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("batchId");

                    b.HasKey("ProductId", "BatchId");

                    b.HasIndex("BatchId");

                    b.ToTable("ProductBatches", (string)null);
                });

            modelBuilder.Entity("ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("productCategories", (string)null);
                });

            modelBuilder.Entity("ProductCoupon", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int>("CouponId")
                        .HasColumnType("int")
                        .HasColumnName("couponId");

                    b.HasKey("ProductId", "CouponId");

                    b.HasIndex("CouponId");

                    b.ToTable("ProductCoupons", (string)null);
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.Common.Modification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Modifications");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.Identity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AttributeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("attributeName");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int")
                        .HasColumnName("createBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date")
                        .HasColumnName("createTime");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int")
                        .HasColumnName("deleteBy");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("isDelete")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.AttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AttributeId")
                        .HasColumnType("int")
                        .HasColumnName("attributeId");

                    b.Property<string>("AttributeValue1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("attributeValue");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int")
                        .HasColumnName("createBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date")
                        .HasColumnName("createTime");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int")
                        .HasColumnName("deleteBy");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("CreateBy");

                    b.ToTable("AttributeValues");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("batchNumber");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int")
                        .HasColumnName("createBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date")
                        .HasColumnName("createTime");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int")
                        .HasColumnName("deleteBy");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiryDate");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("isDelete")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("date")
                        .HasColumnName("manufacturingDate");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("categoryName");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int")
                        .HasColumnName("createBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date")
                        .HasColumnName("createTime");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int")
                        .HasColumnName("deleteBy");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("isDelete")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parentId");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("CouponDescripiton")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("couponDescripiton");

                    b.Property<DateTime?>("CouponEndDate")
                        .HasColumnType("date")
                        .HasColumnName("couponEndDate");

                    b.Property<DateTime?>("CouponStartDate")
                        .HasColumnType("date")
                        .HasColumnName("couponStartDate");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int")
                        .HasColumnName("createBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date")
                        .HasColumnName("createTime");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int")
                        .HasColumnName("deleteBy");

                    b.Property<int?>("DiscountType")
                        .HasColumnType("int")
                        .HasColumnName("discountType");

                    b.Property<double?>("DiscountValue")
                        .HasColumnType("float")
                        .HasColumnName("discountValue");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("isDelete")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int")
                        .HasColumnName("createBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date")
                        .HasColumnName("createTime");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int")
                        .HasColumnName("deleteBy");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstName");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)")
                        .HasColumnName("fullName")
                        .HasComputedColumnSql("(([firstName]+' ')+[lastName])", false);

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("isDelete")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastName");

                    b.Property<int?>("MembershipTypeId")
                        .HasColumnType("int")
                        .HasColumnName("membershipTypeId");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("phoneNumber")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.HasIndex("MembershipTypeId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int")
                        .HasColumnName("createBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date")
                        .HasColumnName("createTime");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int")
                        .HasColumnName("deleteBy");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstName");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)")
                        .HasColumnName("fullName")
                        .HasComputedColumnSql("(([firstName]+' ')+[lastName])", false);

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("isDelete")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastName");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int")
                        .HasColumnName("createBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date")
                        .HasColumnName("createTime");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerID");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int")
                        .HasColumnName("deleteBy");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoiceDate");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("isDelete")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("paymentMethod");

                    b.Property<int?>("PaymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("paymentStatus");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float")
                        .HasColumnName("totalPrice");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.InvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoiceId");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float")
                        .HasColumnName("totalPrice");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float")
                        .HasColumnName("unitPrice");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variantId");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantId");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.MemberShipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("MemberShipTypes");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BarCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("barCode")
                        .IsFixedLength();

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int")
                        .HasColumnName("createBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date")
                        .HasColumnName("createTime");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int")
                        .HasColumnName("deleteBy");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("isDelete")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("ProductImage")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("productImage");

                    b.Property<string>("ProductName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("productName");

                    b.Property<string>("ProductSlug")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("productSlug");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.StockIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int")
                        .HasColumnName("createBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date")
                        .HasColumnName("createTime");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int")
                        .HasColumnName("deleteBy");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entryDate");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("isDelete")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplierId");

                    b.Property<double?>("TotalOrderValue")
                        .HasColumnType("float")
                        .HasColumnName("totalOrderValue");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.HasIndex("SupplierId");

                    b.ToTable("StockIns");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.StockInDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int?>("QuantityReceived")
                        .HasColumnType("int")
                        .HasColumnName("quantityReceived");

                    b.Property<int?>("StockInId")
                        .HasColumnType("int")
                        .HasColumnName("stockInId");

                    b.Property<double?>("TotalValueReceived")
                        .HasColumnType("float")
                        .HasColumnName("totalValueReceived");

                    b.Property<double?>("UnitPriceReceived")
                        .HasColumnType("float")
                        .HasColumnName("unitPriceReceived");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variantId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockInId");

                    b.HasIndex("VariantId");

                    b.ToTable("StockInDetails");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int")
                        .HasColumnName("createBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date")
                        .HasColumnName("createTime");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int")
                        .HasColumnName("deleteBy");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("isDelete")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("phoneNumber")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.UnitConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int")
                        .HasColumnName("createBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date")
                        .HasColumnName("createTime");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int")
                        .HasColumnName("deleteBy");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("isDelete")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("UnitName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unitName");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variantId");

                    b.HasKey("Id");

                    b.HasIndex("CreateBy");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantId");

                    b.ToTable("UnitConversions");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AttributeValueId")
                        .HasColumnType("int")
                        .HasColumnName("attributeValueId");

                    b.Property<double?>("BuyingPrice")
                        .HasColumnType("float")
                        .HasColumnName("buyingPrice");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int")
                        .HasColumnName("createBy");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date")
                        .HasColumnName("createTime");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int")
                        .HasColumnName("deleteBy");

                    b.Property<string>("ImageProductVariant")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("imageProductVariant");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("isDelete")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<double?>("SalePrice")
                        .HasColumnType("float")
                        .HasColumnName("salePrice");

                    b.Property<string>("Sku")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("sku")
                        .IsFixedLength();

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AttributeValueId");

                    b.HasIndex("CreateBy");

                    b.HasIndex("ProductId");

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.Token.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Expriaton")
                        .HasColumnType("datetime")
                        .HasColumnName("expriaton");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("VariantBatch", b =>
                {
                    b.Property<int>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variantId");

                    b.Property<int>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("batchId");

                    b.HasKey("VariantId", "BatchId")
                        .HasName("PK_VaritionBatches");

                    b.HasIndex("BatchId");

                    b.ToTable("VariantBatches", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductBatch", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductBatches_Batches");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductBatches_Products");
                });

            modelBuilder.Entity("ProductCategory", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_productCategories_Categories");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_productCategories_Products");
                });

            modelBuilder.Entity("ProductCoupon", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductCoupons_Coupons");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductCoupons_Products");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.Common.Modification", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithMany("Modifications")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Attribute", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithMany("Attributes")
                        .HasForeignKey("CreateBy")
                        .HasConstraintName("FK_Attributes_AppUsers_Create");

                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.AttributeValue", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Attribute", "Attribute")
                        .WithMany("AttributeValues")
                        .HasForeignKey("AttributeId")
                        .HasConstraintName("FK_AttributeValues_Attributes2");

                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithMany("AttributeValues")
                        .HasForeignKey("CreateBy")
                        .HasConstraintName("FK_AttributeValues_AppUsers_Create");

                    b.Navigation("AppUsers");

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Batch", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithMany("Batches")
                        .HasForeignKey("CreateBy")
                        .HasConstraintName("FK_Batches_AppUsers_Create");

                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Category", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithMany("Categories")
                        .HasForeignKey("CreateBy")
                        .HasConstraintName("FK_Categories_AppUsers_Create");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Categories_Categories");

                    b.Navigation("AppUsers");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Coupon", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithMany("Coupons")
                        .HasForeignKey("CreateBy")
                        .HasConstraintName("FK_Coupons_AppUsers_Create");

                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Customer", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithMany("Customers")
                        .HasForeignKey("CreateBy")
                        .HasConstraintName("FK_Customers_AppUsers_Create");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.MemberShipType", "MembershipType")
                        .WithMany("Customers")
                        .HasForeignKey("MembershipTypeId")
                        .HasConstraintName("FK_Customers_membershipType");

                    b.Navigation("AppUsers");

                    b.Navigation("MembershipType");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Employee", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithOne("Employee")
                        .HasForeignKey("Supermarket.Domain.Entities.SupermarketEntities.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employees_AppUsers");

                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Invoice", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithMany("Invoices")
                        .HasForeignKey("CreateBy")
                        .HasConstraintName("FK_Invoices_AppUsers_Create");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Invoices_Customers");

                    b.Navigation("AppUsers");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.InvoiceDetail", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceDetails_Invoices");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Product", "Product")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceDetails_Products");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Variant", "Variant")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("FK_InvoiceDetails_Variants");

                    b.Navigation("Invoice");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Product", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithMany("Products")
                        .HasForeignKey("CreateBy")
                        .HasConstraintName("FK_Products_AppUsers_Create");

                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.StockIn", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithMany("StockIns")
                        .HasForeignKey("CreateBy")
                        .HasConstraintName("FK_StockIns_AppUsers_Create");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Supplier", "Supplier")
                        .WithMany("StockIns")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK_StockIns_Suppliers");

                    b.Navigation("AppUsers");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.StockInDetail", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Product", "Product")
                        .WithMany("StockInDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_StockInDetails_Products");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.StockIn", "StockIn")
                        .WithMany("StockInDetails")
                        .HasForeignKey("StockInId")
                        .HasConstraintName("FK_StockInDetails_StockIns");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Variant", "Variant")
                        .WithMany("StockInDetails")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("FK_StockInDetails_Variants");

                    b.Navigation("Product");

                    b.Navigation("StockIn");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Supplier", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithMany("Suppliers")
                        .HasForeignKey("CreateBy")
                        .HasConstraintName("FK_Suppliers_AppUsers_Create");

                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.UnitConversion", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithMany("UnitConversions")
                        .HasForeignKey("CreateBy")
                        .HasConstraintName("FK_UnitConversions_AppUsers_Create");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Product", "Product")
                        .WithMany("UnitConversions")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_UnitConversions_Products");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Variant", "Variant")
                        .WithMany("UnitConversions")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("FK_UnitConversions_Variants");

                    b.Navigation("AppUsers");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Variant", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.AttributeValue", "AttributeValue")
                        .WithMany("Variants")
                        .HasForeignKey("AttributeValueId")
                        .HasConstraintName("FK_Variants_AttributeValues");

                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUsers")
                        .WithMany("Variants")
                        .HasForeignKey("CreateBy")
                        .HasConstraintName("FK_Variants_AppUsers_Create");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_VaritionOptions_Products");

                    b.Navigation("AppUsers");

                    b.Navigation("AttributeValue");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.Token.RefreshToken", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.Identity.AppUser", "AppUser")
                        .WithOne("RefreshToken")
                        .HasForeignKey("Supermarket.Domain.Entities.Token.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("VariantBatch", b =>
                {
                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("FK_VaritionBatches_Batches");

                    b.HasOne("Supermarket.Domain.Entities.SupermarketEntities.Variant", null)
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .IsRequired()
                        .HasConstraintName("FK_VariantBatches_Variants");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.Identity.AppUser", b =>
                {
                    b.Navigation("AttributeValues");

                    b.Navigation("Attributes");

                    b.Navigation("Batches");

                    b.Navigation("Categories");

                    b.Navigation("Coupons");

                    b.Navigation("Customers");

                    b.Navigation("Employee")
                        .IsRequired();

                    b.Navigation("Invoices");

                    b.Navigation("Modifications");

                    b.Navigation("Products");

                    b.Navigation("RefreshToken")
                        .IsRequired();

                    b.Navigation("StockIns");

                    b.Navigation("Suppliers");

                    b.Navigation("UnitConversions");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Attribute", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.AttributeValue", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Category", b =>
                {
                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.MemberShipType", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Product", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("StockInDetails");

                    b.Navigation("UnitConversions");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.StockIn", b =>
                {
                    b.Navigation("StockInDetails");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Supplier", b =>
                {
                    b.Navigation("StockIns");
                });

            modelBuilder.Entity("Supermarket.Domain.Entities.SupermarketEntities.Variant", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("StockInDetails");

                    b.Navigation("UnitConversions");
                });
#pragma warning restore 612, 618
        }
    }
}
